databaseType = "Sqlite"
id = "1b204273-9adb-4cf1-801e-7d512af94e80"
name = "flytest2"

[flyway]
callbackLocations = [ "filesystem:callbacks" ]
locations = [ "filesystem:migrations" ]
mixed = true
outOfOrder = false
schemaModelLocation = "schema-model"
validateMigrationNaming = true
environment = "development"

  [flyway.check]
  majorTolerance = 0

[flywayDesktop]
developmentEnvironment = "development"
shadowEnvironment = "shadow"

[redgateCompare]
filterFile = "filter.rgf"
